deploy auto

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -58,6 +58,8 @@ if ! git diff-index --quiet HEAD --; then
     echo "Changes to the following files are uncommitted:"
     git diff-index --name-only HEAD --
     echo "Please commit the changes before proceeding."
+    echo "Aborting."
+    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
 # Switch to source branch (creates it if necessary from the current branch)
